export const SET_SIGNUP = 'SET_SIGNUP'
export const SET_SIGNOUT = 'SET_SIGNOUT'
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP'

export const SET_ADMIN_LOGIN = 'SET_ADMIN_LOGIN'
export const SET_ADMIN_LOGOUT = 'SET_ADMIN_LOGOUT'

export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_USER_RETRIEVE_TOKEN = 'SET_USER_RETRIEVE_TOKEN'
export const DELETE_USER_TOKEN = 'DELETE_USER_TOKEN'

export const SET_ADMIN_TOKEN = 'SET_ADMIN_TOKEN'
export const SET_ADMIN_RETRIEVE_TOKEN = 'SET_ADMIN_RETRIEVE_TOKEN'
export const DELETE_ADMIN_TOKEN = 'DELETE_ADMIN_TOKEN'

export const SET_PROFILE = 'SET_PROFILE'
export const SET_ADMIN_PROFILE = 'SET_ADMIN_PROFILE'
export const SET_ADMIN_UPDATE = 'SET_ADMIN_UPDATE'

export const VIEW_MOVIES = 'VIEW_MOVIES'
export const VIEW_MOVIE = 'VIEW_MOVIE'
export const SET_MOVIES = 'SET_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'

export const SET_SHOW = 'SET_SHOW'
export const SET_BOOK = 'SET_BOOK'
export const SET_BOOKING_STATUS = 'SET_BOOKING_STATUS'
export const SET_BOOKINGS = 'SET_BOOKINGS'

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_SIGN_UP = 'SET_SIGN_UP'
export const SET_SEAT_ERROR = 'SET_SEAT_ERROR'
