export const SET_LOGIN = 'SET_LOGIN'
export const SET_LOGOUT = 'SET_LOGOUT'
export const SET_SIGNUP = 'SET_SIGNUP'
export const SET_SIGNOUT = 'SET_SIGNOUT'
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP'
export const SET_ADMIN_LOGIN = 'SET_ADMIN_LOGIN'
export const SET_ADMIN_LOGOUT = 'SET_ADMIN_LOGOUT'